### PR TITLE
JSON reader

### PR DESCRIPTION
**Pull request by galsalomon66**
(1) the reader based on `rapidjson` (https://github.com/Tencent/rapidjson/ )
(2) https://github.com/Tencent/rapidjson/ resides on s3select as submodule
(3) the s3select JSON reader, is a sax reader, it parses token-by-token. (no preload, no read-ahead) upon key-value is discovered, it saves into a dedicated container. 
(3.a) main assumption: the input JSON is streamed into the JSON reader, the reader is not "aware" of input size. 
(4) following tasks: key-value filter (eventually the filter is set according to the query).

Signed-off-by: root <gal.salomon@gmail.com>
Co-authored-by: Albin Antony <aantony@redhat.com>

### CODE REVIEW

**Comment by cbodley** [comment]
ceph already has a rapidjson submodule that's used by rgw. i would really hope that s3select doesn't need to duplicate that again.. rgw would be including two different versions of the same library

it's probably worth investigating whether rapidjson packages are available in ceph's supported distros, so we could drop the submodule and rely on system packages instead. then cmake would just need `find_package(RapidJSON REQUIRED)` in s3select and ceph. this works fine on fedora with `rapidjson-devel` installed

**Comment by galsalomon66** [comment]
> ceph already has a rapidjson submodule that's used by rgw. i would really hope that s3select doesn't need to duplicate that again.. rgw would be including two different versions of the same library
> 
> it's probably worth investigating whether rapidjson packages are available in ceph's supported distros, so we could drop the submodule and rely on system packages instead. then cmake would just need `find_package(RapidJSON REQUIRED)` in s3select and ceph. this works fine on fedora with `rapidjson-devel` installed

yes, I know RGW already includes `rapidjson`, and the plan was to use that (not to include in s3select-repo as currently done)
but...
I found out there were differences between the `rapidjson` we use and the package version (RGW).
it is mainly about the iterative parsing(token-by-token) which is essential (no preload, no read-ahead, parsing the input per incoming chunk).

**Comment by cbodley** [comment]
> I found out there were differences between the `rapidjson` we use and the package version (RGW).

okay, i see that you're using version 1.1.0. this is the same version in [centos 8 stream](https://centos.pkgs.org/8/getpagespeed-x86_64/rapidjson-devel-1.1.0-12.el8.x86_64.rpm.html) and [ubuntu focal](https://packages.ubuntu.com/focal/rapidjson-dev), so we (both rgw and s3select) should be able to switch to the system packages instead. i pushed https://github.com/ceph/ceph/pull/45818 to try it out

**Comment by galsalomon66** [comment]
work continues on #102

**Pull request closed without merging**
